export const JA_TRANSLATIONS = {
  ja: {
    // サインイン画面
    'Username': 'ユーザー名',
    'Password': 'パスワード',
    'Email Address *': 'メールアドレス *',
    'Enter your phone_number': '電話番号を入力してください',
    'Enter your Username': 'ユーザー名を入力してください',
    'Enter your Password': 'パスワードを入力してください',
    'Confirm Password': 'パスワードを確認',
    'Please confirm your Password': 'パスワードを再入力してください',
    'Reset Password': 'パスワードのリセット',
    'Enter your username': 'ユーザー名を入力してください',
    'Sign In': 'サインイン',
    'Sign in': 'サインイン',
    'Sign Up': 'サインアップ',
    'Forgot your password?': 'パスワードをお忘れの方',
    'Reset password': 'パスワードをリセット',
    'No account?': 'アカウントを持っていない方',
    'Create account': 'アカウントを作成',
    'Create Account': 'アカウントを作成',
    'Have an account?': 'アカウントお持ちの方',
    'Confirm Sign up': 'サインアップの確認',
    'Back to Sign In': 'サインインに戻る',
    'Send code': 'コードを送信',
    'Sign in to your account': 'アカウントにサインイン',
    'Enter your confirmation code': '確認コードを入力してください',
    'Enter your new password': '新しいパスワードを入力してください',
    'Enter your password': 'パスワードを入力してください',
    'Confirm': '確認',
    'Confirmation Code': '確認コード',
    'Resend Code': 'コードを再送',
    'We Emailed You': 'メールを送信しました',
    'Enter your code': '認証コード',

    // パスワードポリシー関連（これが重要！）
    'Password must have at least 8 characters': 'パスワードは8文字以上にしてください',
    'Your passwords must match': 'パスワードが一致しません',
    'Password did not conform with policy: Password not long enough': 'パスワードは8文字以上にしてください',
    'Password does not conform to policy: Password not long enough': 'パスワードは8文字以上を入力してください',
    'Password does not conform to policy: Password must have uppercase characters': 'パスワードには大文字を含めてください',
    'Password does not conform to policy: Password must have lowercase characters': 'パスワードには小文字を含めてください',
    'Password does not conform to policy: Password must have numeric characters': 'パスワードには数字を含めてください',
    'Password does not conform to policy: Password must have symbol characters': 'パスワードには特殊文字を含めてください',

    // エラーメッセージ
    'User does not exist': 'ユーザーが存在しません',
    'User does not exist.': 'ユーザーが存在しません',
    'Username cannot be empty': 'ユーザー名は必須入力です',
    'Password cannot be empty': 'パスワードは必須入力です',
    'Incorrect username or password.': 'ユーザー名またはパスワードが違います',
    'User is not confirmed.': 'ユーザーは確認されていません',
    'User already exists': 'ユーザーは既に存在します',
    'Invalid verification code provided, please try again.': '確認コードが無効です。もう一度お試しください',
    'An account with the given email already exists.': 'そのメールアドレスは既に存在します',
    'Attempt limit exceeded, please try after some time.': '試行制限を超過しました。しばらくしてからもう一度お試しください',
  }
};